apiVersion: 1

datasources:
  - name: GhostAI-S3-Summary
    type: marcusolsson-json-datasource
    access: proxy
    isDefault: true
    jsonData:
      queryParams: ""
    secureJsonData: {}
    editable: false

  - name: GhostAI-S3-Findings
    type: marcusolsson-json-datasource
    access: proxy
    isDefault: false
    jsonData:
      queryParams: ""
    secureJsonData: {}
    editable: false
