#!/usr/bin/env bash
# =============================================================
# FILE: scripts/generate_packetbeat_config.sh
# VERSION: 1.0.0
# UPDATED: 2026-04-18
# OWNER: Giggso Inc
# PURPOSE: Generate packetbeat.yml with correct S3 output and
#          domain filters built from unauthorized.csv.
#          Filter applied at agent level — only AI-adjacent
#          traffic ships to S3. Critical for 10K desktop scale.
# USAGE: bash scripts/generate_packetbeat_config.sh <bucket> <region> <company>
# =============================================================

set -euo pipefail

BUCKET="${1:-marauder-scan-company}"
REGION="${2:-us-east-1}"
COMPANY="${3:-company}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="$REPO_DIR/packetbeat.yml"

# Extract domains from unauthorized.csv
# Column 3 is the domain column — skip header, skip empty, skip port-only rows
DOMAINS=()
if [ -f "$REPO_DIR/config/unauthorized.csv" ]; then
  while IFS=',' read -r name category domain port severity notes; do
    domain=$(echo "$domain" | tr -d '"' | tr -d ' ')
    if [ -n "$domain" ] && [ "$domain" != "domain" ]; then
      # Strip wildcard prefix for contains match
      clean=$(echo "$domain" | sed 's/^\*\.//')
      DOMAINS+=("$clean")
    fi
  done < <(tail -n +2 "$REPO_DIR/config/unauthorized.csv")
fi

# Build contains filter block
DOMAIN_FILTERS=""
for domain in "${DOMAINS[@]}"; do
  DOMAIN_FILTERS="${DOMAIN_FILTERS}            - contains:
                destination.domain: \"${domain}\"
"
done

# Known AI server ports from unauthorized.csv port-only rows
PORT_FILTERS="            - equals:
                destination.port: 11434
            - equals:
                destination.port: 1234
            - equals:
                destination.port: 8080
"

cat > "$OUTPUT" <<EOF
# =============================================================
# Packetbeat configuration — PatronAI
# Generated by scripts/generate_packetbeat_config.sh
# Company: ${COMPANY}
# Bucket:  ${BUCKET}
# Region:  ${REGION}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT EDIT MANUALLY — regenerate via setup.sh
# =============================================================

packetbeat.interfaces.device: any
packetbeat.interfaces.snaplen: 1514

# Protocols to monitor
packetbeat.protocols:
  - type: http
    ports: [80, 443, 8080, 8501, 3000, 8000, 8443, 5000]
    send_request: false
    send_response: false
    hide_keywords: []

  - type: dns
    ports: [53]
    include_authorities: true
    include_additionals: false

# Filter — only ship AI-adjacent traffic to S3
# Applied at agent level — reduces S3 write volume by ~99%
processors:
  - drop_event:
      when:
        not:
          or:
${DOMAIN_FILTERS}${PORT_FILTERS}

  # Add company tag to all events
  - add_fields:
      target: ''
      fields:
        company: "${COMPANY}"
        scanner: "marauder-scan"

# Output — ship directly to S3 via Kinesis Firehose
output.elasticsearch:
  enabled: false

output.logstash:
  enabled: false

# Use file output locally — Kinesis agent picks up and ships to S3
output.file:
  enabled: true
  path: "/var/log/packetbeat"
  filename: "packetbeat"
  rotate_every_kb: 10240
  number_of_files: 7
  codec.json:
    pretty: false

# Logging
logging.level: warning
logging.to_files: true
logging.files:
  path: /var/log/packetbeat
  name: packetbeat.log
  keepfiles: 3

# Performance — keep memory footprint small
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s
EOF

echo "packetbeat.yml generated → $OUTPUT"
echo "Domains filtered: ${#DOMAINS[@]}"
